'''
This script is used to batch change the fps of videos (e.g., the animations generated by LabGym).


How to use:
Use 'cd' command to navigate to where this script locates,
then type 'python3 change_fps.py'


dependencies:

OpenCV

python3 -m pip install opencv-python
'''




###################################################################
# to customize by users

path_to_videos='path to the folder that stores all the videos'
out_path='the output path'
fps_change_factor=5 # the factor will be multiplied, for example, if it is 5, the new fps will be 5 times faster

###################################################################



import cv2
import os



def change_fps(path_to_videos,out_path,fps_change_factor=5):

	for video in os.listdir(path_to_videos):

		if video.endswith('.avi'):

			path_to_video=os.path.join(path_to_videos,video)

			capture=cv2.VideoCapture(path_to_video)
			fps=capture.get(cv2.CAP_PROP_FPS)
			width=int(capture.get(cv2.CAP_PROP_FRAME_WIDTH))
			height=int(capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
			writer=cv2.VideoWriter(os.path.join(out_path,video),cv2.VideoWriter_fourcc(*'MJPG'),fps*fps_change_factor,(width,height),True)

			while True:

				retval,frame=capture.read()
				if frame is None:
					break

				writer.write(frame)

			capture.release()
			writer.release()



change_fps(path_to_videos,out_path,fps_change_factor=fps_change_factor)


